### ISSUE TITLE
error: namespace 'rlang' 0.4.11 is being loaded, but >= 1.0.1 is required

### ISSUE THREAD

**Issue by chenwenyan2015** [dingruofan/xQTLbiolinks#1]
solution: 
Install the package `xQTLbiolinks` in R.
R is working properly but R studio is not working.

**Comment by dingruofan** [comment]
Yes, package 'rlang' is loaded when Rstudio lanched, so it can not be updated when it is in use. Please upate or reinstall 'rlang' in R.
