### ISSUE TITLE
issue with xQTLdownload_eqtlAllAssoPos

### ISSUE THREAD

**Issue by Lymots** [dingruofan/xQTLbiolinks#11]
Hi,
Thank you for your package! I used xQTLdownload_eqtlAllAssoPos as follow:

coloc <- xQTLdownload_eqtlAllAssoPos(
+   chrom = "chr1",
+   pos_lower = 54039447,
+   pos_upper = 56064852,
+   p_upper = 5e-08,
+   tissueLabel = "Whole Blood",
+   study = "gtex_v8",
+   recordPerChunk = 1000,
+   withB37VariantId = TRUE
+ )

It went well and I got the data. However, when I checked the data, the position of the data seemed not be filtered. 
<img width="810" alt="image" src="https://github.com/dingruofan/xQTLbiolinks/assets/130299485/91b96678-ce06-44b4-8c55-be0bfdf59e6b">

Can you help me solve this problem?
Thank you so much.

**Comment by dingruofan** [comment]
Thank you for letting us knowing about this bug, it is caused by the update of eQTL catalogue API links, I will fix this bug as promptly.
