### ISSUE TITLE
xQTLdownload_xqtlAllAsso: Error in download.file(

### ISSUE THREAD

**Issue by mumdark** [dingruofan/xQTLbiolinks#13]
感谢开发如此卓越的工具！

我在运行如下示例代码时遇到报错：

```
xQTLdownload_xqtlAllAsso(genes = c("MMP7"),
                         tissue = "Lung")
```

> Error in download.file(input, tmpFile, method = method, mode = "wb", quiet = !showProgress) : 
  无法打开URL'http://bioinfo.szbl.ac.cn/aQTL/for_xQTLbiolinks/hg38_3UTR_anno.txt'

**Comment by dingruofan** [comment]
Thank you for reporting the bug in my package! I have fixed this, please reinstall the package from the github. If you have any other issues, please don't hesitate to let me know right away.

**Comment by dingruofan** [comment]
has been solved!
