### ISSUE TITLE
AF is renamed to MAF

### ISSUE THREAD

**Issue by chenyangjjj** [dingruofan/xQTLbiolinks#15]
Hi, Thanks for providing this nice tool!

Here is a small report:

In Case study: colocalization analysis in prostate cancer: AF column in gwasDF means effect allele frequency.

While in 
sentinelSnpDF <- xQTLanalyze_getSentinelSnp(gwasDF, centerRange=1e6,
                                            genomeVersion="grch37", grch37To38=TRUE)
The AF column is directly renamed to "MAF" column.
<img width="1123" alt="image" src="https://github.com/dingruofan/xQTLbiolinks/assets/44012383/f556171b-b4c0-4b2d-aac5-cc379c51bf18">

**Comment by Huizhong1993** [comment]
Hello, I have also encountered a similar problem. In the following loop, I did not obtain any data using the example code and cannot proceed to the next step
![微信截图_20240325163809](https://github.com/dingruofan/xQTLbiolinks/assets/150062363/d5b415a9-5178-41e3-81e6-08f2a0a74d0e)

**Comment by dingruofan** [comment]
has been solved!
