### ISSUE TITLE
Error in file(con, "r") : 无法打开链结

### ISSUE THREAD

**Issue by baoshanTan** [dingruofan/xQTLbiolinks#16]
> eQTL_sig1 <- xQTLquery_eqtlSig("rs201327123")
<img width="295" alt="Snipaste_2024-03-23_01-38-52" src="https://github.com/dingruofan/xQTLbiolinks/assets/81540477/f020cf1c-adbb-4fbe-98c3-35bb94fb7c5c">

使用范例，提示无法打开

补充：我重新安装了您的包，并设置了清华镜像与VPN环境，多次运行后仍然提示无法打开，请问这个是因为什么情况呢？

感谢！

**Comment by dingruofan** [comment]
抱歉，服务器端的一些配置文件丢失了，我们正在紧急修复中！

**Comment by dingruofan** [comment]
已经修复了！
