### ISSUE TITLE
None eQTL associations obtained

### ISSUE THREAD

**Issue by Y-Isaac** [dingruofan/xQTLbiolinks#18]
Hi,

I try to run code in quick start, but I failed to get eQTL data of gene _ENSG00000109684_, and I try this in several gene which also failed. Can you confirm if the code is working properly?

The complete log is as follows:

> output <- xQTLanalyze_coloc(data1, "ENSG00000109684", tissueSiteDetail=tissueSiteDetail) # using gene symbol
> Data processing...
> ==> gencodeId
> ==> require gencodeId...
> Querying genes... | 2024-4月-02 14:06:51 
> 1 record has been obtained!
> == Start downloading eQTLs...
> == Downloading eQTL of  ENSG00000109684.14 ...    > Failed...   > Success!
> 
> == combine results...
>  | geneENSG00000109684has no eqtl associations, next!
>  = None eQTL associations obtained of gene [ENSG00000109684], please change the gene name or ENSEMBLE ID.

 
Best,
Issac

**Comment by dingruofan** [comment]
has been solved!
