### ISSUE TITLE
xQTLvisual_locusCombine error

### ISSUE THREAD

**Issue by fmurgia** [dingruofan/xQTLbiolinks#2]
Hi,

I'm using 'xQTLvisual_locusCombine' to plot some results and I'm getting this error  

== Retrieve LD information of SNP: [rs9893278]...
Error in .local(drv, ...) :
  Failed to connect to database: Error: Can't connect to MySQL server on 'locuscompare-us-west-2a.cvocub39nnri.us-west-2.rds.amazonaws.com:3306' (110)

Similar, if I try the example from the documentation I'm getting the same error

ld <- retrieveLD('6', 'rs9349379', 'AFR')
Error in .local(drv, ...) : 
  Failed to connect to database: Error: Can't connect to server on 'locuscompare-us-west-2a.cvocub39nnri.us-west-2.rds.amazonaws.com' (10060)

Any suggestions?

**Comment by dingruofan** [comment]
Dear fmurgia,

Thank you for notifying me about the bugs in my code. I appreciate your help in identifying these issues.

I plan to fix these bugs as soon as possible. I expect to have an update available within 2 days. 

Thank you again for bringing these issues to my attention.

Best regards,
Ruofan

**Comment by dingruofan** [comment]
The package has been updated to v1.4.1, please update using 
```
if(!require("remotes")){install.packages("remotes")}
remotes::install_github("dingruofan/xQTLbiolinks")
```
The `xQTLvisual_xxx` functions retrieve data from a cloud server, but may experience instability at times. It is recommended to try accessing the functions more times.
