### ISSUE TITLE
Can xQTL achieve colocalization under the susie framework?

### ISSUE THREAD

**Issue by Y-Isaac** [dingruofan/xQTLbiolinks#21]
Hi, this is a really nice tool, thanks for your effort!

I want to consult that if xQTL can achieve colocalization under the susie framework which is like coloc5 to solve the "_one causal SNP one locus_" hypothesis? And I asol want to know that if there is a faster way to download eQTL summary data here? I tried downloading in a loop, but it seems a bit slow.

Thanks for your help in advance!

**Comment by dingruofan** [comment]
Currently, our xQTL tool does not directly implement the SuSiE framework for colocalization like coloc5. However, integrating SuSiE or similar approaches is something we are considering for future updates to improve the tool's functionality.
