### ISSUE TITLE
Question about single-cell eQTL

### ISSUE THREAD

**Issue by JiaruiMi01** [dingruofan/xQTLbiolinks#23]
Dear Ruofan and Professor Lei Li,

First thank you for developing such an all-in-one tool for the xQTL analyses, very easy to work with,

Regarding the single-cell eQTL data, I am wondering are there any ways to include more datasets in the repository for the software to search for. Notice that most of the single-cell eQTL are from the blood cells and the brain. 

We are working on the gastrointestinal diseases and are particularly interested in the eQTL data in the liver, pancreas, small intestine and colon. If you think it is possible to include more datasets, I can send you the publication PMID.

Thanks again,
best,
Jiarui MI

**Comment by dingruofan** [comment]
Thank you for your kind words and for using our tool for your xQTL analyses. We are glad to hear that you find it easy to work with. If you could send us the publication PMIDs for the datasets you are interested in, we will evaluate their suitability for inclusion and explore the possibility of integrating them into the repository.

**Comment by JiaruiMi01** [comment]
That is great! Since I am working on endocrinology and gastroenterology, I can name a few datasets which were recently available. 

1, PMID: 34644572, Cell Rep. 2021 Oct 12;37(2):109807. doi: 10.1016/j.celrep.2021.109807.
2, PMID: 37903777, Nat Commun. 2023 Oct 30;14(1):6928. doi: 10.1038/s41467-023-42560-4.
3, PMID: 32999275, Nat Commun. 2020 Sep 30;11(1):4912. doi: 10.1038/s41467-020-18581-8.
4, PMID: 36693378, Am J Hum Genet. 2023 Feb 2;110(2):284-299. doi: 10.1016/j.ajhg.2023.01.002.

I will get you updated when I come across new dataset in the digestive tissues.

all the best,
Jiarui
