### ISSUE TITLE
Question about the missing datasets for the annotation function

### ISSUE THREAD

**Issue by JiaruiMi01** [dingruofan/xQTLbiolinks#24]
Dear Ruofan and Professor Lei Li, 

Another small question, I noticed that the software also implement several modules in annotation, which include:
xQTLanno_genomic: https://dingruofan.github.io/xQTLbiolinks/reference/xQTLvisual_anno.html
xQTLanno_chippeak: https://dingruofan.github.io/xQTLbiolinks/reference/xQTLanno_chippeak.html
xQTLanno_calLambda: https://dingruofan.github.io/xQTLbiolinks/reference/xQTLanno_calLambda.html

However, when I run the demo, I noticed that several files required for the analyses were missing on the websites, which include:
http://bioinfo.szbl.ac.cn/xQTL_biolinks/xqtl_data/gwas/gwasSub.txt.gz
http://bioinfo.szbl.ac.cn/xQTL_biolinks/xqtl_data/enhancer.txt
http://bioinfo.szbl.ac.cn/xQTL_biolinks/xqtl_data/eqtl/MMP7_qtlDF.txt

And in the tutorial, there should be another folder named "eQTL" under the xQTL_biolinks directory. 

Would it be possible that you can reorganize the background files on your website?

Thank you very much for your time and attention. 

all the best,
Jiarui

**Comment by dingruofan** [comment]
I’ve reorganized the background files on the website, and they should now be accessible
