### ISSUE TITLE
None eQTL associations obtained

### ISSUE THREAD

**Issue by szkgg** [dingruofan/xQTLbiolinks#25]
Hi,

I try to run code in quick start, but I failed to get eQTL data of gene SULF1, and I try this in several gene which also failed. Can you confirm if the code is working properly?

The complete log is as follows:

== Tissue label [Lung] detected...
== Check the gene name:
Querying genes... | 2024-7月-11 00:13:00 
1 record has been obtained!
== Done.
== Start fetching associations...
=> Download failed and try again...1/3
=> Download failed and try again...2/3
Warning messages:
1: In readBin(14L, raw(0), 32768L) :
  URL 'http://www.ebi.ac.uk/eqtl/api/genes/ENSG00000136381/associations?links=False&tissue=UBER_0008952&size=1000&start=0': Timeout of 60 seconds was reached
2: In open.connection(con, "rb") :
  URL 'https://www.ebi.ac.uk/eqtl/api/genes/ENSG00000136381/associations?links=False&tissue=UBER_0008952&size=1000&start=0': Timeout of 60 seconds was reached
3: In open.connection(con, "rb") :
  URL 'https://www.ebi.ac.uk/eqtl/api/genes/ENSG00000136381/associations?links=False&tissue=UBER_0008952&size=1000&start=0': status was 'SSL connect error'

Best,
Erkang Yi

**Comment by dingruofan** [comment]
I have tested the code on my end, and it appears to be functioning correctly. Please try running the code again after reinstalling xQTLbiolinks.
![image](https://github.com/user-attachments/assets/39fd46fb-8fcb-4848-a136-6228256b166e)
