### ISSUE TITLE
Is there any way to use eQTL database other than GTEx and can I read eGene tables from local files？

### ISSUE THREAD

**Issue by Stray357** [dingruofan/xQTLbiolinks#3]
Hi,
Thank you for your great package. I've been following the steps on your tutorial at https://dingruofan.github.io/xQTLbiolinks/articles/Quick_start.html
 And found out that in step 3 'Identify trait genes for each sentinel SNPs'. The function automatically reduced genes to trait genes included in GTEx eGenes, the consideration to reduce the number of trait is really great, but if I would like to use eQTL database other than GTEx, this may cause unwanted reduction in my included gene pool. Is there any way I can skip the overlap process, or is there other ways to use eQTL database other than GTEx ？

The other problem is also about the xQTLanalyze_getTraits() function. The internet condition is literally nightmare  in my region, and I'm tired of staring at the error 'File download error'. Is there anyway I can pre-download the data needed and query that from my local directory?

Thanks a lot !

**Comment by dingruofan** [comment]
Hi,

Thank you for your message and I’m glad to hear that you find our package useful.

I will modify the functions you motioned above to further optimize the package in two days.

**Comment by Stray357** [comment]
Thank you very much for your reply, looking forward to your update
