### ISSUE TITLE
Can you please include the eye eQTL data?

### ISSUE THREAD

**Issue by Mahantesh-Biradar** [dingruofan/xQTLbiolinks#5]
Can you please include the eye eQTL data?

**Comment by dingruofan** [comment]
We can include the eye eQTL data or other kinds of QTL datasets, but the datasets must be publicly available or have been authorized for use. We need to ensure that we are using reliable and credible data sources to avoid any potential issues with data accuracy or data privacy.

**Comment by Mahantesh-Biradar** [comment]
Hello, I wanted to check if you have any updates on this? TIA

**Comment by dingruofan** [comment]
I apologize for the delay in my response. The package is currently undergoing peer review and therefore cannot be updated at the moment. I will include dataset in the package once the review is complete. Thank you for your understanding.

**Comment by Mahantesh-Biradar** [comment]
Hi, I just wanted to check if the eQTL data? thanks

**Comment by dingruofan** [comment]
sorry, I don't find eye eQTL data in GTEx, could please show more details of the data source?
