### ISSUE TITLE
xQTLvisual_geneExpTissues("TP53") does not plot expression of the defined gene in vlnplot.

### ISSUE THREAD

**Issue by bhuwankhatri11** [dingruofan/xQTLbiolinks#6]
Hi,
Thank you for the nicest tool. However, I used _xQTLvisual_geneExpTissues("TP53")_ to plot the expression of TP53 genes in different tissues but did not get it plotted. It throughs the following error-
```
Error in `palette()`:
! Insufficient values in manual scale. 54 needed but only 30
  provided.
Run `rlang::last_trace()` to see where the error occurred.
```
Will you please guide me to overcome this error? Thanks!

bk11

**Comment by dingruofan** [comment]
Hi, thanks for your comments. After debugging the codes, I have solved this issue. 
Please reinstall the package from the github using 
`devtools::[install_github](https://remotes.r-lib.org/reference/install_github.html)("dingruofan/xQTLbiolinks")`
