### ISSUE TITLE
lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by Jak-stat** [dingruofan/xQTLbiolinks#7]
hi，
Thank u for this useful tool! However, when i tried to obtain eqtl data from online datasets（for example “xQTLdownload_eqtlAllAsso”）, the following error occurred:
lexical error: invalid char in json text.
                                       <!DOCTYPE html> <html lang="en"
                     (right here) ------^
And this new problem has not occurred before.  Would you please help fix this error? Thank u so much!

![error](https://github.com/dingruofan/xQTLbiolinks/assets/52615723/1d439ce8-db8d-407f-9cf2-3ed216e7fe9c)

**Comment by shuang-pi-ji** [comment]
I have the same problem. Is it the change of url ?

**Comment by dingruofan** [comment]
Sorry for the inconvenience caused by the GTEx Portal API update, which has resulted in some functions of xQTLbioliks to malfunction. The package will be updated within one week to address this issue.

**Comment by dingruofan** [comment]
The GTEx Portal API update has caused some functions of xQTLbioliks to malfunction. The package will be updated within one week to address this issue.

**Comment by dingruofan** [comment]
I have resolved this issue by updating the API links. Please reinstall the package using `devtools::install_github("dingruofan/xQTLbiolinks")`. If you encounter any new bugs or errors, please do not hesitate to inform me.
